### PR TITLE
disable studio mode

### PR DESCRIPTION
**Pull request by sabuto**
Made sense to have a disable studio mode method seeing as there in an enable

### CODE REVIEW

**Comment by faithoflifedev** [comment]
Do you mind updating the "Supported high-level commands" section of the README, to reflect this change.  Once that's in place then I can merge in the changes.

Also FYI, the current published version includes your previous submissions.

Thanks for your help.

**Comment by faithoflifedev** [comment]
Another FYI, I've just renamed "master" to "main" so you may need to make some local changes.  Here's what I needed to do - https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes

**Comment by sabuto** [comment]
sure thing i'll do this tomorrow :), no worries i am using this for an app so thought i would contribute :D Thanks for the link

**Comment by sabuto** [comment]
updated the readme :)

**Pull request merged**
